name: ${PROJECT_NAME}-production

services:
  application:
    build:
      context: ./../../
      dockerfile: ./docker/development/images/application.dockerfile
    restart: unless-stopped

  server:
    build:
      context: ./../../
      dockerfile: ./docker/development/images/server.dockerfile
    ports:
      - 80:80
    depends_on:
      - application
    restart: unless-stopped

networks:
  default:
    name: ${PROJECT_NAME}-production
